services:
  nginx:
    image: nginx:alpine
    container_name: rs_nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - rs_network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: rs_php
    volumes:
      - ./backend:/var/www
    working_dir: /var/www
    networks:
      - rs_network

  mysql:
    image: mysql:8.0
    container_name: rs_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: resource_saas
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: saas_user
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - rs_mysql_data:/var/lib/mysql
    networks:
      - rs_network

  redis:
    image: redis:alpine
    container_name: rs_redis
    ports:
      - "6379:6379"
    networks:
      - rs_network

networks:
  rs_network:
    driver: bridge

volumes:
  rs_mysql_data:
